language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.2
    - android-28


  notifications:
    email: false

before_install:
  - yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;28.0.3"