language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.2
    - android-28

  licenses:
    - 'android-sdk-license-.+'

  notifications:
    email: false
